<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\Question::insert([
            [              "test_id"=> 34,
              "question"=> "彼女は子供の時、（行儀）作法を家庭で厳しく教え込まれた。",
              "image"=> null,
              "answer1"=> "ぎょうぎ",
              "answer2"=> "こうぎ",
              "answer3"=> "ぎょうき",
              "answer4"=> "こうき",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [              "test_id"=> 34,
              "question"=> "国際コンクールでの優勝は、若い音楽家の人生を（一瞬）にして変えた。",
              "image"=> null,
              "answer1"=> "いつしゅん",
              "answer2"=> "いっじゅん",
              "answer3"=> "いちしゅん",
              "answer4"=> "いっしゅん",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [              "test_id"=> 34,
              "question"=> "「残りわずか」の声に（誘われて）、思わずテレビショッピングで買い物をしてしまった。",
              "image"=> null,
              "answer1"=> "とらわれて",
              "answer2"=> "うたわれて",
              "answer3"=> "さそわれて",
              "answer4"=> "おそわれて",
              "correct_answer"=> "answer3",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [              "test_id"=> 34,
              "question"=> "以前は静かな町だったのに、最近は（物騒）な事件が多くなった。",
              "image"=> null,
              "answer1"=> "ぶっそう",
              "answer2"=> "ぶつそう",
              "answer3"=> "ぶっぞう",
              "answer4"=> "ぶつぞう",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [              "test_id"=> 34,
              "question"=> "インフルエンザでの死亡率が低い理由の一つに、国民の（衛生）知識の高さがあげられる。",
              "image"=> null,
              "answer1"=> "ええせい",
              "answer2"=> "えいせい",
              "answer3"=> "えいぜい",
              "answer4"=> "ええぜい",
              "correct_answer"=> "answer2",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [              "test_id"=> 34,
              "question"=> "節約生活に疲れた消防者に安いだけの商品は（あきられて）きた。",
              "image"=> null,
              "answer1"=> "飲きられて",
              "answer2"=> "飯きられて",
              "answer3"=> "館きられて",
              "answer4"=> "飽きられて",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [              "test_id"=> 34,
              "question"=> "「源氏物語」は日本の代表的な（こてん）文学だ。",
              "image"=> null,
              "answer1"=> "古典",
              "answer2"=> "古展",
              "answer3"=> "箇典",
              "answer4"=> "個展",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [              "test_id"=> 34,
              "question"=> "自分の欠点を（なげいて）ばかりいないで、長所を伸ばすべきだ。",
              "image"=> null,
              "answer1"=> "嘆いて",
              "answer2"=> "漢いて",
              "answer3"=> "喝いて",
              "answer4"=> "難いて",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [              "test_id"=> 34,
              "question"=> "ストレスの多い現代、うつ病をい痛む人が（げきぞう）している。",
              "image"=> null,
              "answer1"=> "激増",
              "answer2"=> "劇象",
              "answer3"=> "劇増",
              "answer4"=> "激象",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 34,
              "question"=> "高い技術力のおかげで海水が（たんすい）化されて、飲めるようになった。",
              "image"=> null,
              "answer1"=> "短水",
              "answer2"=> "単水",
              "answer3"=> "探水",
              "answer4"=> "淡水",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "自分の手で文字を書くと記憶（＿＿）がより高まるそうだ。",
              "image"=> null,
              "answer1"=> "性",
              "answer2"=> "力",
              "answer3"=> "質",
              "answer4"=> "化",
              "correct_answer"=> "answer2",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "この絵は彼の代表（＿＿）である。",
              "image"=> null,
              "answer1"=> "者",
              "answer2"=> "品",
              "answer3"=> "作",
              "answer4"=> "物",
              "correct_answer"=> "answer3",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "ここは高山植物の保護（＿＿）です。",
              "image"=> null,
              "answer1"=> "場",
              "answer2"=> "区",
              "answer3"=> "域",
              "answer4"=> "所",
              "correct_answer"=> "answer2",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "プロ野球の公式（＿＿）が始まるところだ。",
              "image"=> null,
              "answer1"=> "権",
              "answer2"=> "陣",
              "answer3"=> "軍",
              "answer4"=> "戦",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "この薬は胃を荒らす（＿＿）作用がある。",
              "image"=> null,
              "answer1"=> "反",
              "answer2"=> "副",
              "answer3"=> "複",
              "answer4"=> "悪",
              "correct_answer"=> "answer2",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "「歴史は繰り返す」と言うが、同じように繰り返されることは（＿＿）にない。",
              "image"=> null,
              "answer1"=> "滅多",
              "answer2"=> "眼中",
              "answer3"=> "たま",
              "answer4"=> "まれ",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "洗濯機がこう（＿＿）故障するのでは、買い替えるしかない。",
              "image"=> null,
              "answer1"=> "とうとう",
              "answer2"=> "ぞくぞく",
              "answer3"=> "それぞれ",
              "answer4"=> "しばしば",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "この地域は一人暮らしのお年寄りが多く、（＿＿）に不安がある。",
              "image"=> null,
              "answer1"=> "オペレーション",
              "answer2"=> "セキュリティー",
              "answer3"=> "コンタクト",
              "answer4"=> "コンデイション",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "私の夢は、グローバルな（＿＿）で活躍することです。",
              "image"=> null,
              "answer1"=> "舞台",
              "answer2"=> "信頼",
              "answer3"=> "資本",
              "answer4"=> "現実",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 35,
              "question"=> "この家の建て方は、この地方（＿＿）のものです。",
              "image"=> null,
              "answer1"=> "格別",
              "answer2"=> "独特",
              "answer3"=> "特殊",
              "answer4"=> "特例",
              "correct_answer"=> "answer2",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "屋根を（＿＿）するついでに、太陽光発電システムを取り入れることにした。",
              "image"=> null,
              "answer1"=> "修繕",
              "answer2"=> "修正",
              "answer3"=> "調節",
              "answer4"=> "管理",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "新聞の料理記事の（＿＿）を献立の参考にしている。",
              "image"=> null,
              "answer1"=> "選り抜き",
              "answer2"=> "切り取り",
              "answer3"=> "書き取り",
              "answer4"=> "切り抜き",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "この私鉄は次の駅でJRと連絡している。",
              "image"=> null,
              "answer1"=> "交差している",
              "answer2"=> "一体化している",
              "answer3"=> "乗り換えになる",
              "answer4"=> "つながっている",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "選挙の予想が（外れた）。",
              "image"=> null,
              "answer1"=> "難しかった",
              "answer2"=> "騒がれた",
              "answer3"=> "当たらなかった",
              "answer4"=> "おかしかった",
              "correct_answer"=> "answer3",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "近道したのに（かえって）時間がかかった。",
              "image"=> null,
              "answer1"=> "多少",
              "answer2"=> "逆に",
              "answer3"=> "非常に",
              "answer4"=> "改めて",
              "correct_answer"=> "answer2",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "（はっきり）意見を申し上げるなら、その案には反対です。",
              "image"=> null,
              "answer1"=> "適当に",
              "answer2"=> "簡単に",
              "answer3"=> "率直に",
              "answer4"=> "自由に",
              "correct_answer"=> "answer3",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
          
              "test_id"=> 36,
              "question"=> "上司が休日出勤して、部下の遅れた仕事を（カバーした）。",
              "image"=> null,
              "answer1"=> "進めた",
              "answer2"=> "引き受けた",
              "answer3"=> "終わらせた",
              "answer4"=> "補った",
              "correct_answer"=> "answer4",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "通用",
              "image"=> null,
              "answer1"=> "この仕事には能力のある人物を通用する予定だ。",
              "answer2"=> "そんなへたな言い訳は、私には通用しない。",
              "answer3"=> "この危険な仕事に、これだけの給料では通用しない。",
              "answer4"=> "この本はあなたの勉強に通用するのでお読みなさい。",
              "correct_answer"=> "answer2",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "あらすじ",
              "image"=> null,
              "answer1"=> "この小説のあらすじを400字以内にまとめなさい。",
              "answer2"=> "仲間同士で激しいあらすじになってしまった。",
              "answer3"=> "論文は、あらすじ書き上がっています。",
              "answer4"=> "会議で経営方針のあらすじが決まった。",
              "correct_answer"=> "answer1",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
              "test_id"=> 36,
              "question"=> "迷惑",
              "image"=> null,
              "answer1"=> "誰にでも迷惑な思い出の1つや2つはあるものだ。",
              "answer2"=> "込んでいる電車の中で新聞を広げるのは、他の客に迷惑だ。",
              "answer3"=> "病気だと分かった時にはもうすでに手遅れで、迷惑な状態だった。",
              "answer4"=> "こんな少ない給料では家族の生活はいい迷惑だ。",
              "correct_answer"=> "answer2",
              "created_at"=> \Carbon\Carbon::now(),
              "detail_answer" => "detail_answer",
              "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 7,
                "question"=> "",
                "image"=> "https://japanesetest4you.com/image/2009_02_listen_quiz1.jpg",
                "answer1"=> "1",
                "answer2"=> "2",
                "answer3"=> "3",
                "answer4"=> "4",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ], 
            [
            "test_id"=> 7,
            "question"=> "https://japanesetest4you.com/image/2009_02_listen_quiz2.jpg",
            "image"=> "",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer1",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ], 
            [
            "test_id"=> 7,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/2009_02_listen_quiz3.jpg",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer3",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ], 
            [
            "test_id"=> 7,
            "question"=> "https://japanesetest4you.com/image/2009_02_listen_quiz4.jpg",
            "image"=> "",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer2",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ], 
            [
            "test_id"=> 7,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/2009_02_listen_quiz5.jpg",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer2",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 7,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/2009_02_listen_quiz6.jpg",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer2",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 7,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/2009_02_listen_quiz7.jpg",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer4",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 7,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/2009_02_listen_quiz8.jpg",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer1",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 7,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/2009_02_listen_quiz9.jpg",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer2",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 7,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/2009_02_listen_quiz10.jpg",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer4",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 9,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/jlpt-n2-listening-3-01.gif",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer4",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 9,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/jlpt-n2-listening-3-02.gif",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer3",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 9,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/jlpt-n2-listening-3-03.gif",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer2",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 9,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/jlpt-n2-listening-3-04.gif",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer3",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 9,
            "question"=> "",
            "image"=> "https://japanesetest4you.com/image/jlpt-n2-listening-3-05.gif",
            "answer1"=> "1",
            "answer2"=> "2",
            "answer3"=> "3",
            "answer4"=> "4",
            "correct_answer"=> "answer3",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 37,
                "question"=> "_______ な資金は、安定した経営、さらに事業拡大できるチャンスにつながります。",
                "image"=> null,
                "answer1"=> "豊富",
                "answer2"=> "贅沢",
                "answer3"=> "幸福",
                "answer4"=> "多量",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "シジンは真面目な時は本当に真面目なのですが、ちゃっかりした面や、_______ が好きな面もあり、それも私と似ているかもしれません。",
                "image"=> null,
                "answer1"=> "評判",
                "answer2"=> "快適",
                "answer3"=> "確認",
                "answer4"=> "冗談",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "受話器を置いた大統領は、前進する _______ ができていた。",
                "image"=> null,
                "answer1"=> "覚悟",
                "answer2"=> "感覚",
                "answer3"=> "発覚",
                "answer4"=> "自覚",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "僕はすばらしいデザインを見れば元気になるし、_______ 工程のわずかな違いにまでこだわる。",
                "image"=> null,
                "answer1"=> "造作",
                "answer2"=> "製造",
                "answer3"=> "創造",
                "answer4"=> "製品",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "彼がここに電話をかけてきたのは単なる _______ の一致かもしれない。",
                "image"=> null,
                "answer1"=> "自然",
                "answer2"=> "天然",
                "answer3"=> "突然",
                "answer4"=> "偶然",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "二度とあの部屋に入らないと約束しろ _______ 言われたけど、僕は約束しなかった。",
                "image"=> null,
                "answer1"=> "を",
                "answer2"=> "って",
                "answer3"=> "のを",
                "answer4"=> "だ",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "私は何百回もこの手紙を読み返した。そして読み返す　_______ たまらなく哀しい気持になった。",
                "image"=> null,
                "answer1"=> "うちに",
                "answer2"=> "はじめに",
                "answer3"=> "たびに",
                "answer4"=> "だけに",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "本を読んでいたら、　_______ 五時間も経ってしまった。",
                "image"=> null,
                "answer1"=> "そろそろ",
                "answer2"=> "だんだん",
                "answer3"=> "ようやく",
                "answer4"=> "いつの間にか",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "ふたりはそれから３０年あまり、死がふたりを分かつまで幸せな結婚生活を送る　_______ 。",
                "image"=> null,
                "answer1"=> "ことだ",
                "answer2"=> "ことになった",
                "answer3"=> "ことにした",
                "answer4"=> "ようになった",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 37,
                "question"=> "彼女が蛇口をあけ、僕の傷ついた前腕を氷　_______ 冷たい水の下へ導いた。",
                "image"=> null,
                "answer1"=> "のように",
                "answer2"=> "みたいに",
                "answer3"=> "のときに",
                "answer4"=> "そうに",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "資金の _______ を突き止めれば、テロリストを突き止め、制圧することができる。",
                "image"=> null,
                "answer1"=> "連れ",
                "answer2"=> "哀れ",
                "answer3"=> "流れ",
                "answer4"=> "恐れ",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "私は農家の長男なのですが、父が商業高校への _______ を勧めてくれたのです。",
                "image"=> null,
                "answer1"=> "通学",
                "answer2"=> "進学",
                "answer3"=> "留学",
                "answer4"=> "奨学",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "後輩に仕事のやり方について _______ をしました。",
                "image"=> null,
                "answer1"=> "アイデア",
                "answer2"=> "アドバイス",
                "answer3"=> "デザイン",
                "answer4"=> "イメージ",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "セミナーに参加したい人は、_______ に住所、氏名、希望日を書いてください。",
                "image"=> null,
                "answer1"=> "証明書",
                "answer2"=> "領収書",
                "answer3"=> "申込書",
                "answer4"=> "参考書",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "私は、外国語を１日で _______ マスターしたい。",
                "image"=> null,
                "answer1"=> "完成",
                "answer2"=> "完了",
                "answer3"=> "完全",
                "answer4"=> "完璧",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "まさかあのふたり　_______ なにかあったと言いたいんじゃないだろうな！",
                "image"=> null,
                "answer1"=> "の間と",
                "answer2"=> "の間の",
                "answer3"=> "の間に",
                "answer4"=> "の間で",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "鍵はお客様のお部屋のテーブルの上に　_______ 。",
                "image"=> null,
                "answer1"=> "ございます",
                "answer2"=> "いらっしゃいます",
                "answer3"=> "いる",
                "answer4"=> "おります",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "あなた　_______ ちょっと内密で話したいことがあるのですが…",
                "image"=> null,
                "answer1"=> "だけ",
                "answer2"=> "だけで",
                "answer3"=> "だけを",
                "answer4"=> "だけに",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "勉強して、ある程度日本が話せる　_______ 日本語の授業がおもしろくなった。",
                "image"=> null,
                "answer1"=> "ことができるまで",
                "answer2"=> "ことができてから",
                "answer3"=> "ようになるまで",
                "answer4"=> "ようになってから",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 38,
                "question"=> "A社の商品が腰の痛みにどのくらい効果が　_______ 詳しく知りたい。",
                "image"=> null,
                "answer1"=> "あるのかによって",
                "answer2"=> "あるのかについて",
                "answer3"=> "あるのかどうかによって",
                "answer4"=> "あるのかどうかについて",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "企業がインターネット広告にかける「費用」は年々増加している。",
                "image"=> null,
                "answer1"=> "オーバー",
                "answer2"=> "コスト",
                "answer3"=> "エネルギー",
                "answer4"=> "グランド",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "わたしはこの馬の美しさに魅せられ、「帰宅」してからインターネットで調べてみた。",
                "image"=> null,
                "answer1"=> "家に帰る",
                "answer2"=> "会社に行く",
                "answer3"=> "国に戻る",
                "answer4"=> "学校に通う",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "あれは僕が「望む」仕事ではなかった。個人に製品を売れない状況に、本当に気が滅入ってしまった。",
                "image"=> null,
                "answer1"=> "願う",
                "answer2"=> "祈る",
                "answer3"=> "想う",
                "answer4"=> "図る",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "特に懸念されている点の一つは、市場が「拡大」することだ。",
                "image"=> null,
                "answer1"=> "成長",
                "answer2"=> "拡張",
                "answer3"=> "発展",
                "answer4"=> "進化",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "壁は告知や「証明」書でごちゃごちゃしていて、大きな時計がやかましくカチカチ鳴っている。",
                "image"=> null,
                "answer1"=> "デモ",
                "answer2"=> "プルーフ",
                "answer3"=> "カスタム",
                "answer4"=> "アナウンス",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "笑顔を浮かべて「機嫌」がいいふりをする必要はない。",
                "image"=> null,
                "answer1"=> "様子",
                "answer2"=> "具合",
                "answer3"=> "調子",
                "answer4"=> "気分",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "実験がうまくいかなかったので、「やりなおした」。",
                "image"=> null,
                "answer1"=> "やり方を調べた",
                "answer2"=> "やり方を教わった",
                "answer3"=> "もう一度やった",
                "answer4"=> "やるのを途中でやめた",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "このことは、「ないしょにしてください」。",
                "image"=> null,
                "answer1"=> "だれにも話さないで",
                "answer2"=> "いろいろな人に話して",
                "answer3"=> "早く忘れて",
                "answer4"=> "忘れないで",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "あのスーパーは、「年中」、セールをしている。",
                "image"=> null,
                "answer1"=> "最近",
                "answer2"=> "いつも",
                "answer3"=> "ときどき",
                "answer4"=> "前から",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 39,
                "question"=> "彼が留学したのは、大学卒業の「翌年」です。",
                "image"=> null,
                "answer1"=> "前の前の年",
                "answer2"=> "次の次の年",
                "answer3"=> "前の年",
                "answer4"=> "次の年",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 40,
                "question"=> "有名",
                "image"=> "",
                "answer1"=> " ゆめい",
                "answer2"=> " ゆうめい",
                "answer3"=> " ゆうめ",
                "answer4"=> " ゆめ",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "写真家",
                "image"=> "",
                "answer1"=> " しゃしんか",
                "answer2"=> " さしんか",
                "answer3"=> " さしんや",
                "answer4"=> " しゃしんや",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "世界",
                "image"=> "",
                "answer1"=> " せかく",
                "answer2"=> " せいかく",
                "answer3"=> " せいかい",
                "answer4"=> " せかい",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "鳥",
                "image"=> "",
                "answer1"=> " むし",
                "answer2"=> " とり",
                "answer3"=> " しま",
                "answer4"=> " うま",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "動物",
                "image"=> "",
                "answer1"=> " しょくぶつ",
                "answer2"=> " せいぶつ",
                "answer3"=> " どうぶつ",
                "answer4"=> " こうぶつ",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "行われて",
                "image"=> "",
                "answer1"=> " さそわれて",
                "answer2"=> " いわれて",
                "answer3"=> " おこなわれて",
                "answer4"=> " あらわれて",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "医者",
                "image"=> "",
                "answer1"=> " いしゃ",
                "answer2"=> " いし",
                "answer3"=> " いっしゃ",
                "answer4"=> " いっし",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "働き",
                "image"=> "",
                "answer1"=> " はたらき",
                "answer2"=> " みがき",
                "answer3"=> " いただき",
                "answer4"=> " うごき",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "注意",
                "image"=> "",
                "answer1"=> " ちゅうい",
                "answer2"=> " しゅい",
                "answer3"=> " ちゅい",
                "answer4"=> " しゅうい",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 40,
                "question"=> "言われ",
                "image"=> "",
                "answer1"=> " きわれ",
                "answer2"=> " さわれ",
                "answer3"=> " いわれ",
                "answer4"=> " やわれ",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "私はどうしても家に帰らなければ　_______ 。",
                "image"=> "",
                "answer1"=> " いかない",
                "answer2"=> " ならない",
                "answer3"=> " なってない",
                "answer4"=> " いってない",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "窓の外では雨が　_______ いる。",
                "image"=> "",
                "answer1"=> " 降りつづけて",
                "answer2"=> " 降ってつづけて",
                "answer3"=> " 降るつづけて",
                "answer4"=> " 降ったつづけて",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "高木くんはこの仕事が気に入らなかった　_______ だけど、僕はとっても楽しかったです。",
                "image"=> "",
                "answer1"=> " みたい",
                "answer2"=> " のみたい",
                "answer3"=> " にみたい",
                "answer4"=> " なみたい",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "生まれた　_______ の子牛が立ち上がり、歩こうとしている。",
                "image"=> "",
                "answer1"=> " だけ",
                "answer2"=> " とき",
                "answer3"=> " ところ",
                "answer4"=> " ばかり",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "このじしょはここ　_______ つかってください。",
                "image"=> "",
                "answer1"=> " に",
                "answer2"=> " の",
                "answer3"=> " で",
                "answer4"=> " を",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "しゃべりたくない　_______ 、　しゃべらなくてもいいですよ。",
                "image"=> "",
                "answer1"=> " のたら",
                "answer2"=> " のなら",
                "answer3"=> " のと",
                "answer4"=> " のは",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "中国を旅しているあいだ、実家への連絡はあまり　_______ 。",
                "image"=> "",
                "answer1"=> " した",
                "answer2"=> " しなかった",
                "answer3"=> " していた",
                "answer4"=> " していなかった",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "機械工作をすごいと言ったけど、鈴木は手を　_______ 。",
                "image"=> "",
                "answer1"=> " 汚しがらなかった",
                "answer2"=> " 汚したくなかった",
                "answer3"=> " 汚したがらなくなった",
                "answer4"=> " 汚したがらなかった",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "駅へ行きたいんですが、どう　_______ いいですか。",
                "image"=> "",
                "answer1"=> " 行って",
                "answer2"=> " 行けば",
                "answer3"=> " 行くなら",
                "answer4"=> " 行くのは",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 41,
                "question"=> "けさはいつもより早く学校へ行きました。しかし、山田さんはもう　_______ 。",
                "image"=> "",
                "answer1"=> " きます",
                "answer2"=> " きています",
                "answer3"=> " きてでした",
                "answer4"=> " きていました",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "あの人は病気ではない　_______ くすりをたくさん飲んでいます。",
                "image"=> "",
                "answer1"=> " ので",
                "answer2"=> " ために",
                "answer3"=> " のに",
                "answer4"=> "　から",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "これから日本に行くけど１週間で戻る。戻ったらすぐに会いたいと思う。それまで、なにも　_______ 。",
                "image"=> "",
                "answer1"=> " 決めないようほしい",
                "answer2"=> " 決めないほしい",
                "answer3"=> " 決めなくてほしい",
                "answer4"=> " 決めないでほしい",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "社長から電話が　_______ とき、私は子供とピクニックに出かける準備をしていた。",
                "image"=> "",
                "answer1"=> " かかってきた",
                "answer2"=> " かかっていった",
                "answer3"=> " かかっておいた",
                "answer4"=> " かかってみた",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "でもあなたと話が　_______ よ。だって二人で話をしたことなんて一度もなかったものな。",
                "image"=> "",
                "answer1"=> " できてよい",
                "answer2"=> " できてよかった",
                "answer3"=> " できたらよかった",
                "answer4"=> " できればよかった",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "彼は私たちが部屋に入った　_______ ドアを閉めた。",
                "image"=> "",
                "answer1"=> " ごで",
                "answer2"=> " あとで",
                "answer3"=> " まえで",
                "answer4"=> " まえに",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "このバスは郵便局の前　_______ 通りますか？",
                "image"=> "",
                "answer1"=> " で",
                "answer2"=> " に",
                "answer3"=> " へ",
                "answer4"=> " を",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "この本のほうがあなたには　_______ はずだ。",
                "image"=> "",
                "answer1"=> " わかったやすい",
                "answer2"=> " わかるやすい",
                "answer3"=> " わかりやすい",
                "answer4"=> "わかってやすい",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "電車を待っていたとき、わたしは友だち　_______ 名前を呼ばれました。",
                "image"=> "",
                "answer1"=> " を",
                "answer2"=> " が",
                "answer3"=> " に",
                "answer4"=> " で",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "昨日は仕事を守れる　_______ が不安だった。しかしいまは、命を守れる　_______ が不安だ。",
                "image"=> "",
                "answer1"=> " かどうか/かどうか",
                "answer2"=> " か/か",
                "answer3"=> " じゃないか/じゃないか",
                "answer4"=> " の/の",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 42,
                "question"=> "明日の夕方　_______ 東京に戻りたい。アルバイトに行かなければならないから。",
                "image"=> "",
                "answer1"=> " までで",
                "answer2"=> " まで",
                "answer3"=> " までに",
                "answer4"=> "にまで",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "ちいさい",
                "image"=> "",
                "answer1"=> " 中さい",
                "answer2"=> " 少さい",
                "answer3"=> " 小さい",
                "answer4"=> " 大さい",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "らじお",
                "image"=> "",
                "answer1"=> " ラゾオ",
                "answer2"=> " ラジオ",
                "answer3"=> " ウゾオ",
                "answer4"=> " ウジオ",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "ぽけっと",
                "image"=> "",
                "answer1"=> " ポケット",
                "answer2"=> " パクット",
                "answer3"=> " ポクット",
                "answer4"=> " パケット",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "でかけ",
                "image"=> "",
                "answer1"=> " 外かけ",
                "answer2"=> " 行かけ",
                "answer3"=> " 来かけ",
                "answer4"=> " 出かけ",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "でんしゃ",
                "image"=> "",
                "answer1"=> " 電車",
                "answer2"=> " 雷車",
                "answer3"=> " 電東",
                "answer4"=> " 雷東",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "きき",
                "image"=> "",
                "answer1"=> " 聞き",
                "answer2"=> " 開き",
                "answer3"=> " 閉き",
                "answer4"=> " 間き",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "かいしゃ",
                "image"=> "",
                "answer1"=> " 社員",
                "answer2"=> " 社会",
                "answer3"=> " 会計",
                "answer4"=> " 会社",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "先",
                "image"=> "",
                "answer1"=> " せん",
                "answer2"=> " つぎ",
                "answer3"=> " すぐ",
                "answer4"=> " さき",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "食べて",
                "image"=> "",
                "answer1"=> " とべて",
                "answer2"=> " のべて",
                "answer3"=> " たべて",
                "answer4"=> " くべて",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 43,
                "question"=> "後で",
                "image"=> "",
                "answer1"=> " あとで",
                "answer2"=> " のちで",
                "answer3"=> " ごで",
                "answer4"=> " こうで",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "この本は　_______ 読みました。",
                "image"=> "",
                "answer1"=> " どう",
                "answer2"=> " もう",
                "answer3"=> " も",
                "answer4"=> " まだ",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "山田さんはたいへんいい人ですよ。なにもわるいことはきいたことが　_______ わ。",
                "image"=> "",
                "answer1"=> " しません",
                "answer2"=> " いません",
                "answer3"=> " なりません",
                "answer4"=> " ありません",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "ここにじゅうしょを書いて　_______ か？",
                "image"=> "",
                "answer1"=> " ください",
                "answer2"=> " くださいます",
                "answer3"=> " くださいません",
                "answer4"=> " くださいましょうか",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "あなたはあそこへ行って　_______ いけませんよ。",
                "image"=> "",
                "answer1"=> " が",
                "answer2"=> " は",
                "answer3"=> " と",
                "answer4"=> " に",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "どれ　_______ ここではたらいていましたか？",
                "image"=> "",
                "answer1"=> " まで",
                "answer2"=> " もう",
                "answer3"=> " より",
                "answer4"=> " くらい",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "わたしはおんがくをきく_______ 好きです。",
                "image"=> "",
                "answer1"=> " のが",
                "answer2"=> " ので",
                "answer3"=> " のに",
                "answer4"=> " のは",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "わたしは一人でクリスマスをすごす _______ です。",
                "image"=> "",
                "answer1"=> " たい",
                "answer2"=> " つもり",
                "answer3"=> " だろう",
                "answer4"=> " ほう",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "_______ ながら水を飲まないでください。",
                "image"=> "",
                "answer1"=> " あるく",
                "answer2"=> " あるいて",
                "answer3"=> " あるき",
                "answer4"=> " あるかな",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "れいぞうこにビールが入っている　_______ 、そこにすわって飲みましょう。",
                "image"=> "",
                "answer1"=> " から",
                "answer2"=> " と",
                "answer3"=> " なら",
                "answer4"=> "たら",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 44,
                "question"=> "わたしのことをいつまでも　_______ ください。",
                "image"=> "",
                "answer1"=> " わすれない",
                "answer2"=> " わすれないて",
                "answer3"=> " わすれなくて",
                "answer4"=> "わすれないで",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "「やまもとさん、_______ はスミスさんです。」「はじめまして。」",
                "image"=> "",
                "answer1"=> " これ",
                "answer2"=> " だれ",
                "answer3"=> " こちら",
                "answer4"=> " どちら",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "あそこにじてんしゃが _______ とまっています。",
                "image"=> "",
                "answer1"=> " いっぴき",
                "answer2"=> " いっさつ",
                "answer3"=> " いちまい",
                "answer4"=> " いちだい",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "かんじのおぼえかたを　_______　ください。",
                "image"=> "",
                "answer1"=> " かんがえて",
                "answer2"=> " おもって",
                "answer3"=> " おしえて",
                "answer4"=> " はしって",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "_______　をさんぽしましょう。",
                "image"=> "",
                "answer1"=> " べんり",
                "answer2"=> " かべ",
                "answer3"=> " ビル",
                "answer4"=> " こうえん",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> " _______　じぶんのくるまをかいたいです。",
                "image"=> "",
                "answer1"=> " だれか",
                "answer2"=> " どこか",
                "answer3"=> " いつか",
                "answer4"=> " なにか",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "もう　_______　ゆっくりいってください。",
                "image"=> "",
                "answer1"=> " いちど",
                "answer2"=> " いくつ",
                "answer3"=> " いちまい",
                "answer4"=> " いっしょに",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "昨日　_______　をしました。",
                "image"=> "",
                "answer1"=> " かみ",
                "answer2"=> " いぬ",
                "answer3"=> " しゅくだい",
                "answer4"=> " とし",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "このりょうりは　_______ です。",
                "image"=> "",
                "answer1"=> " からい",
                "answer2"=> " くらい",
                "answer3"=> " さむい",
                "answer4"=> " みじかい",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "きょうからこのがっこうに　_______　ことになりました。",
                "image"=> "",
                "answer1"=> " かく",
                "answer2"=> " いく",
                "answer3"=> " かよう",
                "answer4"=> " すむ",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 45,
                "question"=> "これはラジカセと　 _______　。",
                "image"=> "",
                "answer1"=> " よびます",
                "answer2"=> " のみます",
                "answer3"=> " よみます",
                "answer4"=> " とびます",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 3,
                "question"=> "それはとあるが、何を指しているか。",
                "image"=> null,
                "answer1"=> "知性",
                "answer2"=> "損得の判断",
                "answer3"=> "内なる声",
                "answer4"=> "倫理",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
            ],
            [
                "test_id"=> 3,
                "question"=> "倫理の原液とあるが、その説明として正しいのはどれか。",
                "image"=> null,
                "answer1"=> "個人の心の中にある社会の役に立ちたいという欲求である。",
                "answer2"=> "人を含む生き物が自分の身を守ろうとする自己保存の本能である。",
                "answer3"=> "人間という知性動物がもつ、集団に適応しようとする欲求である。",
                "answer4"=> "集団を作ってしか生きていけない人間の心に潜む助け合うの欲求である。",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_1.mp3",
                "image"=> null,
                "answer1"=> "水の量を増やす",
                "answer2"=> "水の量を減らす",
                "answer3"=> "ひりょうを増やす",
                "answer4"=> "ひりょうを減らす",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_2.mp3",
                "image"=> null,
                "answer1"=> "ゴミ袋を買う",
                "answer2"=> "清掃用具を買う",
                "answer3"=> "お知らせの内容を書き足す",
                "answer4"=> "役所にゴミ回収を依頼する",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_3.mp3",
                "image"=> null,
                "answer1"=> "パッケージのデザイン",
                "answer2"=> "クリームの種類",
                "answer3"=> "一箱に入れるクッキーの量",
                "answer4"=> "販売価格",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_4.mp3",
                "image"=> null,
                "answer1"=> "一年間の契約をする",
                "answer2"=> "二年件の契約をする",
                "answer3"=> "携帯電話を買い換える",
                "answer4"=> "手数料を払う",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_5.mp3",
                "image"=> null,
                "answer1"=> "野菜を収穫する",
                "answer2"=> "牛の世話をする",
                "answer3"=> "食事の準備をする",
                "answer4"=> "若手グループの話を聞く",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_6.mp3",
                "image"=> null,
                "answer1"=> "商品の開発",
                "answer2"=> "新人研修",
                "answer3"=> "主任研修",
                "answer4"=> "商品の製造",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_7.mp3",
                "image"=> null,
                "answer1"=> "外出するときにマスクをすること",
                "answer2"=> "うがいと手洗いをすること",
                "answer3"=> "体を休めるために十分に寝ること",
                "answer4"=> "えいようがある食事をとること",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_8.mp3",
                "image"=> null,
                "answer1"=> "薬品の量を間違えたこと",
                "answer2"=> "実験の順番を間違えたこと",
                "answer3"=> "温度設定をしなかったこと",
                "answer4"=> "温度設定をしたこと",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_9.mp3",
                "image"=> null,
                "answer1"=> "すでに他社から類似の製品が出ているため",
                "answer2"=> "商品化に莫大な費用がかかるため",
                "answer3"=> "商品化に長時間かかると予想されるから",
                "answer4"=> "買う人が限定されると考えられるため",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 16,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1_10.mp3",
                "image"=> null,
                "answer1"=> "形が個性的なところ",
                "answer2"=> "色の使い方がざんしんなところ",
                "answer3"=> "ブランド品で高級に見えるところ",
                "answer4"=> "値段が手ごろなところ",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_1.mp3",
                "image"=> null,
                "answer1"=> "テレビコマーシャルで商品の説明をする",
                "answer2"=> "商品をテレビドラマに登場させる",
                "answer3"=> "テレビコマーシャルに人気俳優を起用する",
                "answer4"=> "バッケージを目立つデザインにする",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_2.mp3",
                "image"=> null,
                "answer1"=> "ユニークなアイデアが出せること",
                "answer2"=> "皆の前で自分をアピールできること",
                "answer3"=> "議論の流れをふまえた意見が言えること",
                "answer4"=> "専門的知識に基づく意見が言えること",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_3.mp3",
                "image"=> null,
                "answer1"=> "げんそうできな世界を楽しみたいから",
                "answer2"=> "電気代を節約したいから",
                "answer3"=> "省エネへの意識を持ち続けたいから",
                "answer4"=> "家族のきずなが深まるから",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_4.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> 4,
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_5.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> 4,
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_6.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> 4,
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_7.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> 4,
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_8.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> 4,
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_9.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> 4,
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 17,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1b_10.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> 4,
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_1.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_2.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_3.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_4.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_5.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_6.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_7.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_8.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_9.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 18,
                "question"=> "https://japanesetest4you.com/choukai/0008/n1_1c_10.mp3",
                "image"=> null,
                "answer1"=> 1,
                "answer2"=> 2,
                "answer3"=> 3,
                "answer4"=> '',
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "わたしは発作性頭位眩暈症という病気の症状に襲われました。\r\n\r\n発作",
                "image"=> null,
                "answer1"=> "はっさ",
                "answer2"=> "ほっさ",
                "answer3"=> "はっさく",
                "answer4"=> "ほっさく",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "結婚問題にはもう片がついたが、れんあいのほうはそうはいかなかった。\r\n\r\nれんあい",
                "image"=> null,
                "answer1"=> "恋窓",
                "answer2"=> "変愛",
                "answer3"=> "恋愛",
                "answer4"=> "変窓",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "会社が成長する勢いや、事業をとりまく環境などを詳しく分析することで、大幅な値上がりをする株を探し当てるのは、株の大きな楽しみの一つです。\r\n\r\n大幅",
                "image"=> null,
                "answer1"=> "だいふく",
                "answer2"=> "だいはば",
                "answer3"=> "おおふく",
                "answer4"=> "おおはば",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "採択",
                "image"=> null,
                "answer1"=> "せんたく",
                "answer2"=> "さいたく",
                "answer3"=> "さいけつ",
                "answer4"=> "せんけつ",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "にんしんだから休まなきゃいけないのに、いろいろ予定を詰め込んでいます。\r\n\r\nにんしん",
                "image"=> null,
                "answer1"=> "妊辱",
                "answer2"=> "妊辰",
                "answer3"=> "妊娠",
                "answer4"=> "妊振",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "輝かしい経歴のなかで、途方もない本の構想を聞かされたことは何度もある。\r\n\r\n経歴",
                "image"=> null,
                "answer1"=> "けいれき",
                "answer2"=> "けいりき",
                "answer3"=> "たてりき",
                "answer4"=> "たてれき",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "ごみの減量化を市民に訴えるとともに、駅やスーパーなどに空きびんの回収箱を設置することにした。\r\n\r\n回収",
                "image"=> null,
                "answer1"=> "かいしょう",
                "answer2"=> "かいじょう",
                "answer3"=> "かいしゅう",
                "answer4"=> "かいじゅう",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "設置",
                "image"=> null,
                "answer1"=> "せつび",
                "answer2"=> "せっち",
                "answer3"=> "せつりつ",
                "answer4"=> "せってい",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "業績の悪化した会社がゆうしを受けられるチャンスは低いです。だからこそ、創業時はできるだけたくさんの資金を調達しましょう。\r\n\r\nゆうし",
                "image"=> null,
                "answer1"=> "鬲姿",
                "answer2"=> "融姿",
                "answer3"=> "鬲資",
                "answer4"=> "融資",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 31,
                "question"=> "建設業界は団塊の世代の方々が多く、今後建設業の仕事量が減っていくことも予想されています。\r\n\r\n世代",
                "image"=> null,
                "answer1"=> "せだい",
                "answer2"=> "よだい",
                "answer3"=> "よたい",
                "answer4"=> "せたい",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "私の調べたかぎりでは、何人と _______ その男を害することを欲するような理由が、どこにもまったく見あたらないんですよ。",
                "image"=> null,
                "answer1"=> "いえども",
                "answer2"=> "いったらば",
                "answer3"=> "いえばこそ",
                "answer4"=> "いったからには",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "さすがに一流の歌手　_______ 違う。１回の出演料が数百万円だという。",
                "image"=> null,
                "answer1"=> "ともすると",
                "answer2"=> "ともなると",
                "answer3"=> "のはいえ",
                "answer4"=> "といっても",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "車が角を曲がると、橋本は身を起こし、わたしの血　_______ の腕を握った。",
                "image"=> null,
                "answer1"=> "ずくめ",
                "answer2"=> "まみれ",
                "answer3"=> "ばはり",
                "answer4"=> "みずく",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "人前で演技をするのは初めての経験　_______ 、彼はひどく緊張していた。",
                "image"=> null,
                "answer1"=> "とあって",
                "answer2"=> "にあって",
                "answer3"=> "として",
                "answer4"=> "にして",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "コンピュータがデジタルハブになると最初に見 _______ のはわが社だ。",
                "image"=> null,
                "answer1"=> "ぬいて",
                "answer2"=> "ぬく",
                "answer3"=> "ぬいた",
                "answer4"=> "ぬき",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "もう少し早く病院に行けば助かった　_______ 、放っておいたので、手遅れになってしまった。",
                "image"=> null,
                "answer1"=> "もので",
                "answer2"=> "ものか",
                "answer3"=> "ものを",
                "answer4"=> "ものに",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "中村は三杯目のウォッカを飲みほし、キッチンの窓から外を見る　_______ 見た。",
                "image"=> null,
                "answer1"=> "ばかりか",
                "answer2"=> "のみならず",
                "answer3"=> "ともなしに",
                "answer4"=> "どころではなく",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "彼は自分の息子がどうなっているかを、一度　_______ 調べようとはしない。",
                "image"=> null,
                "answer1"=> "よりも",
                "answer2"=> "だけは",
                "answer3"=> "たりとも",
                "answer4"=> "ばかりか",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "子どものころ、死については　_______ だに恐ろしかった。",
                "image"=> null,
                "answer1"=> "考え",
                "answer2"=> "考えた",
                "answer3"=> "考えて",
                "answer4"=> "考える",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 32,
                "question"=> "僕が席に着く　_______ 、彼女が待ってましたとばかりにやって来た。",
                "image"=> null,
                "answer1"=> "次第で",
                "answer2"=> "や否や",
                "answer3"=> "が最後",
                "answer4"=> "末に",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 33,
                "question"=> "インターネット広告 _______ と広告の効果の関係について考えてみよう。",
                "image"=> null,
                "answer1"=> "値",
                "answer2"=> "費",
                "answer3"=> "料",
                "answer4"=> "額",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 33,
                "question"=> "この数年間で千葉や隣接県では女児連れ去り事件が多発していた。まだ _______ 解決の案件もあるが、未遂に終わり、容疑者が逮捕されたケースもある。",
                "image"=> null,
                "answer1"=> "非",
                "answer2"=> "双",
                "answer3"=> "未",
                "answer4"=> "無",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 33,
                "question"=> "辞書を引いたら、最初に _______ されている語義だけでなく、すべての語義をざっと確認する習慣を付けましょう。",
                "image"=> null,
                "answer1"=> "記載",
                "answer2"=> "援用",
                "answer3"=> "参照",
                "answer4"=> "出典",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 33,
                "question"=> "専門学校で、デザインという仕事の難しさに _______ することになりました。",
                "image"=> null,
                "answer1"=> "対決",
                "answer2"=> "直面",
                "answer3"=> "抵抗",
                "answer4"=> "挑戦",
                "correct_answer"=> "answer2",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 33,
                "question"=> "この機械を _______ にはかなりの技術が必要だ。",
                "image"=> null,
                "answer1"=> "使いこなす",
                "answer2"=> "使いおわる",
                "answer3"=> "使いはたす",
                "answer4"=> "使いすてる",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 33,
                "question"=> "最近の青少年はしっかりしているようだが、精神的に _______ 面がある。",
                "image"=> null,
                "answer1"=> "しぶい",
                "answer2"=> "だるい",
                "answer3"=> "ゆるい",
                "answer4"=> "もろい",
                "correct_answer"=> "answer4",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 33,
                "question"=> "何回会議をやっても結論が出ないので、_______ いやになった。",
                "image"=> null,
                "answer1"=> "つくづく",
                "answer2"=> "わざわざ",
                "answer3"=> "ぞくぞくと",
                "answer4"=> "くれぐれも",
                "correct_answer"=> "answer1",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
              [
                "test_id"=> 33,
                "question"=> "不況の影響で、この地域の中小企業は _______ 倒産した。",
                "image"=> null,
                "answer1"=> "いまさら",
                "answer2"=> "ひたすら",
                "answer3"=> "のきなみ",
                "answer4"=> "ひいては",
                "correct_answer"=> "answer3",
                "created_at"=> \Carbon\Carbon::now(),
                "detail_answer" => "detail_answer",
                "updated_at"=> \Carbon\Carbon::now()
              ],
            [
            "test_id"=> 33,
            "question"=> "年をとると、だんだん新しい考え方が _______ にくくなる。",
            "image"=> null,
            "answer1"=> "うけあい",
            "answer2"=> "うけいれ",
            "answer3"=> "うけとり",
            "answer4"=> "うけもち",
            "correct_answer"=> "answer2",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ],
            [
            "test_id"=> 33,
            "question"=> "このアンケートに協力するかしないかは自由で、________ はしないということにしたい。",
            "image"=> null,
            "answer1"=> "圧迫",
            "answer2"=> "強制",
            "answer3"=> "催促",
            "answer4"=> "一致",
            "correct_answer"=> "answer2",
            "created_at"=> \Carbon\Carbon::now(),
            "detail_answer" => "detail_answer",
            "updated_at"=> \Carbon\Carbon::now()
            ]
        ]);
    }
}
