<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\Question::insert([
            [
              "id"=> 1,
              "test_id"=> 34,
              "question"=> "彼女は子供の時、（行儀）作法を家庭で厳しく教え込まれた。",
              "image"=> null,
              "answer1"=> "ぎょうぎ",
              "answer2"=> "こうぎ",
              "answer3"=> "ぎょうき",
              "answer4"=> "こうき",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 2,
              "test_id"=> 34,
              "question"=> "国際コンクールでの優勝は、若い音楽家の人生を（一瞬）にして変えた。",
              "image"=> null,
              "answer1"=> "いつしゅん",
              "answer2"=> "いっじゅん",
              "answer3"=> "いちしゅん",
              "answer4"=> "いっしゅん",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 3,
              "test_id"=> 34,
              "question"=> "「残りわずか」の声に（誘われて）、思わずテレビショッピングで買い物をしてしまった。",
              "image"=> null,
              "answer1"=> "とらわれて",
              "answer2"=> "うたわれて",
              "answer3"=> "さそわれて",
              "answer4"=> "おそわれて",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 4,
              "test_id"=> 34,
              "question"=> "以前は静かな町だったのに、最近は（物騒）な事件が多くなった。",
              "image"=> null,
              "answer1"=> "ぶっそう",
              "answer2"=> "ぶつそう",
              "answer3"=> "ぶっぞう",
              "answer4"=> "ぶつぞう",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 5,
              "test_id"=> 34,
              "question"=> "インフルエンザでの死亡率が低い理由の一つに、国民の（衛生）知識の高さがあげられる。",
              "image"=> null,
              "answer1"=> "ええせい",
              "answer2"=> "えいせい",
              "answer3"=> "えいぜい",
              "answer4"=> "ええぜい",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 6,
              "test_id"=> 34,
              "question"=> "節約生活に疲れた消防者に安いだけの商品は（あきられて）きた。",
              "image"=> null,
              "answer1"=> "飲きられて",
              "answer2"=> "飯きられて",
              "answer3"=> "館きられて",
              "answer4"=> "飽きられて",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 7,
              "test_id"=> 34,
              "question"=> "「源氏物語」は日本の代表的な（こてん）文学だ。",
              "image"=> null,
              "answer1"=> "古典",
              "answer2"=> "古展",
              "answer3"=> "箇典",
              "answer4"=> "個展",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 8,
              "test_id"=> 34,
              "question"=> "自分の欠点を（なげいて）ばかりいないで、長所を伸ばすべきだ。",
              "image"=> null,
              "answer1"=> "嘆いて",
              "answer2"=> "漢いて",
              "answer3"=> "喝いて",
              "answer4"=> "難いて",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 9,
              "test_id"=> 34,
              "question"=> "ストレスの多い現代、うつ病をい痛む人が（げきぞう）している。",
              "image"=> null,
              "answer1"=> "激増",
              "answer2"=> "劇象",
              "answer3"=> "劇増",
              "answer4"=> "激象",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 10,
              "test_id"=> 34,
              "question"=> "高い技術力のおかげで海水が（たんすい）化されて、飲めるようになった。",
              "image"=> null,
              "answer1"=> "短水",
              "answer2"=> "単水",
              "answer3"=> "探水",
              "answer4"=> "淡水",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 11,
              "test_id"=> 34,
              "question"=> "自分の手で文字を書くと記憶（＿＿）がより高まるそうだ。",
              "image"=> null,
              "answer1"=> "性",
              "answer2"=> "力",
              "answer3"=> "質",
              "answer4"=> "化",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 12,
              "test_id"=> 34,
              "question"=> "この絵は彼の代表（＿＿）である。",
              "image"=> null,
              "answer1"=> "者",
              "answer2"=> "品",
              "answer3"=> "作",
              "answer4"=> "物",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 13,
              "test_id"=> 34,
              "question"=> "ここは高山植物の保護（＿＿）です。",
              "image"=> null,
              "answer1"=> "場",
              "answer2"=> "区",
              "answer3"=> "域",
              "answer4"=> "所",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 14,
              "test_id"=> 34,
              "question"=> "プロ野球の公式（＿＿）が始まるところだ。",
              "image"=> null,
              "answer1"=> "権",
              "answer2"=> "陣",
              "answer3"=> "軍",
              "answer4"=> "戦",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 15,
              "test_id"=> 34,
              "question"=> "この薬は胃を荒らす（＿＿）作用がある。",
              "image"=> null,
              "answer1"=> "反",
              "answer2"=> "副",
              "answer3"=> "複",
              "answer4"=> "悪",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 16,
              "test_id"=> 34,
              "question"=> "「歴史は繰り返す」と言うが、同じように繰り返されることは（＿＿）にない。",
              "image"=> null,
              "answer1"=> "滅多",
              "answer2"=> "眼中",
              "answer3"=> "たま",
              "answer4"=> "まれ",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 17,
              "test_id"=> 34,
              "question"=> "洗濯機がこう（＿＿）故障するのでは、買い替えるしかない。",
              "image"=> null,
              "answer1"=> "とうとう",
              "answer2"=> "ぞくぞく",
              "answer3"=> "それぞれ",
              "answer4"=> "しばしば",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 18,
              "test_id"=> 34,
              "question"=> "この地域は一人暮らしのお年寄りが多く、（＿＿）に不安がある。",
              "image"=> null,
              "answer1"=> "オペレーション",
              "answer2"=> "セキュリティー",
              "answer3"=> "コンタクト",
              "answer4"=> "コンデイション",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 19,
              "test_id"=> 34,
              "question"=> "私の夢は、グローバルな（＿＿）で活躍することです。",
              "image"=> null,
              "answer1"=> "舞台",
              "answer2"=> "信頼",
              "answer3"=> "資本",
              "answer4"=> "現実",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 20,
              "test_id"=> 34,
              "question"=> "この家の建て方は、この地方（＿＿）のものです。",
              "image"=> null,
              "answer1"=> "格別",
              "answer2"=> "独特",
              "answer3"=> "特殊",
              "answer4"=> "特例",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 21,
              "test_id"=> 34,
              "question"=> "屋根を（＿＿）するついでに、太陽光発電システムを取り入れることにした。",
              "image"=> null,
              "answer1"=> "修繕",
              "answer2"=> "修正",
              "answer3"=> "調節",
              "answer4"=> "管理",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 22,
              "test_id"=> 34,
              "question"=> "新聞の料理記事の（＿＿）を献立の参考にしている。",
              "image"=> null,
              "answer1"=> "選り抜き",
              "answer2"=> "切り取り",
              "answer3"=> "書き取り",
              "answer4"=> "切り抜き",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 23,
              "test_id"=> 34,
              "question"=> "この私鉄は次の駅でJRと連絡している。",
              "image"=> null,
              "answer1"=> "交差している",
              "answer2"=> "一体化している",
              "answer3"=> "乗り換えになる",
              "answer4"=> "つながっている",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 24,
              "test_id"=> 34,
              "question"=> "選挙の予想が（外れた）。",
              "image"=> null,
              "answer1"=> "難しかった",
              "answer2"=> "騒がれた",
              "answer3"=> "当たらなかった",
              "answer4"=> "おかしかった",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 25,
              "test_id"=> 34,
              "question"=> "近道したのに（かえって）時間がかかった。",
              "image"=> null,
              "answer1"=> "多少",
              "answer2"=> "逆に",
              "answer3"=> "非常に",
              "answer4"=> "改めて",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.093Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 26,
              "test_id"=> 34,
              "question"=> "（はっきり）意見を申し上げるなら、その案には反対です。",
              "image"=> null,
              "answer1"=> "適当に",
              "answer2"=> "簡単に",
              "answer3"=> "率直に",
              "answer4"=> "自由に",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
          
              "id"=> 27,
              "test_id"=> 34,
              "question"=> "上司が休日出勤して、部下の遅れた仕事を（カバーした）。",
              "image"=> null,
              "answer1"=> "進めた",
              "answer2"=> "引き受けた",
              "answer3"=> "終わらせた",
              "answer4"=> "補った",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 28,
              "test_id"=> 34,
              "question"=> "通用",
              "image"=> null,
              "answer1"=> "この仕事には能力のある人物を通用する予定だ。",
              "answer2"=> "そんなへたな言い訳は、私には通用しない。",
              "answer3"=> "この危険な仕事に、これだけの給料では通用しない。",
              "answer4"=> "この本はあなたの勉強に通用するのでお読みなさい。",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 29,
              "test_id"=> 34,
              "question"=> "あらすじ",
              "image"=> null,
              "answer1"=> "この小説のあらすじを400字以内にまとめなさい。",
              "answer2"=> "仲間同士で激しいあらすじになってしまった。",
              "answer3"=> "論文は、あらすじ書き上がっています。",
              "answer4"=> "会議で経営方針のあらすじが決まった。",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 30,
              "test_id"=> 34,
              "question"=> "迷惑",
              "image"=> null,
              "answer1"=> "誰にでも迷惑な思い出の1つや2つはあるものだ。",
              "answer2"=> "込んでいる電車の中で新聞を広げるのは、他の客に迷惑だ。",
              "answer3"=> "病気だと分かった時にはもうすでに手遅れで、迷惑な状態だった。",
              "answer4"=> "こんな少ない給料では家族の生活はいい迷惑だ。",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 31,
              "test_id"=> 34,
              "question"=> "売買",
              "image"=> null,
              "answer1"=> "不動産を売買するには資格が必要だ。",
              "answer2"=> "この店は土日も休まず売買している。",
              "answer3"=> "この商品は売買がよくて、生産が追いつかない。",
              "answer4"=> "やむを得ない事情でこの土地を売買することにした。",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 32,
              "test_id"=> 34,
              "question"=> "過半数",
              "image"=> null,
              "answer1"=> "今回の地震の被害者の数は過半数だった。",
              "answer2"=> "狭い会場にファンが過半数で押しかけてきた。",
              "answer3"=> "新しい法案は過半数の賛成を得たので国会で成立した。",
              "answer4"=> "彼が犯人だという証拠は過半数である。",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 33,
              "test_id"=> 34,
              "question"=> "転職はよく考えた（＿＿）決めたことですから、たとえ失敗してもかまいません。",
              "image"=> null,
              "answer1"=> "あげく",
              "answer2"=> "上で",
              "answer3"=> "ついでに",
              "answer4"=> "際に",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 34,
              "test_id"=> 34,
              "question"=> "税金が上がるのは困る。しかし高齢者がますます増える現実（＿＿）、仕方がない。",
              "image"=> null,
              "answer1"=> "だからといって",
              "answer2"=> "だけあって",
              "answer3"=> "からいって",
              "answer4"=> "といって",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 35,
              "test_id"=> 34,
              "question"=> "ここのタイ料理は、日本人（＿＿）少し辛さをおさえてあります。",
              "image"=> null,
              "answer1"=> "向けに",
              "answer2"=> "用に",
              "answer3"=> "寄りに",
              "answer4"=> "敵に",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 36,
              "test_id"=> 34,
              "question"=> "私が見た（＿＿）、山田さんがそんなに悪い人とは思えない。",
              "image"=> null,
              "answer1"=> "ものでは",
              "answer2"=> "限りでは",
              "answer3"=> "ことでは",
              "answer4"=> "まででは",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 37,
              "test_id"=> 34,
              "question"=> "「自分ならもっとうまくやれる」と言うなら、君がやってみる（＿）だね。",
              "image"=> null,
              "answer1"=> "こと",
              "answer2"=> "はず",
              "answer3"=> "わけ",
              "answer4"=> "もの",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 38,
              "test_id"=> 34,
              "question"=> "結婚後も仕事をする女性が増える（＿＿）、専業主婦になりたい女性も増えている。",
              "image"=> null,
              "answer1"=> "以外で",
              "answer2"=> "反対で",
              "answer3"=> "一方で",
              "answer4"=> "片面で",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 39,
              "test_id"=> 34,
              "question"=> "検査の結果が心配（＿＿）、朝まで寝ることができなかった。",
              "image"=> null,
              "answer1"=> "のおかげで",
              "answer2"=> "のせいか",
              "answer3"=> "のくせに",
              "answer4"=> "のあまり",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 40,
              "test_id"=> 34,
              "question"=> "この果物はとても健康にいい（＿＿）、昔から「医者いらず」とも呼ばれる。",
              "image"=> null,
              "answer1"=> "ことに",
              "answer2"=> "ことから",
              "answer3"=> "ことだから",
              "answer4"=> "ことなら",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 41,
              "test_id"=> 34,
              "question"=> "健康に悪いと（＿＿）、どうしてもタバコがやめられない。",
              "image"=> null,
              "answer1"=> "知らないものの",
              "answer2"=> "しらないくせに",
              "answer3"=> "知りつつも",
              "answer4"=> "知るからには",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 42,
              "test_id"=> 34,
              "question"=> "この中で誰も免許を持っていないから、私が運転（＿＿）ね。",
              "image"=> null,
              "answer1"=> "するべきでない",
              "answer2"=> "しないわけにはいかない",
              "answer3"=> "してはいられない",
              "answer4"=> "するわけにはいかない",
              "correct_answer"=> "answer2",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 43,
              "test_id"=> 34,
              "question"=> "たとえ贈り物が（＿＿）、下さった方にお礼の手紙くらい書くものですよ。",
              "image"=> null,
              "answer1"=> "きに入ったとしたら",
              "answer2"=> "気に入らないかったとしたら",
              "answer3"=> "気に入らなかったにしても",
              "answer4"=> "気に入ったとしても",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 44,
              "test_id"=> 34,
              "question"=> "A=> [あいにく田中は外出しております。」B：では、A 社の山田から電話があったと（＿＿）。",
              "image"=> null,
              "answer1"=> "お伝えいただけますか",
              "answer2"=> "お伝えになれますか",
              "answer3"=> "お伝えいたしましょうか",
              "answer4"=> "伝えていただきますか",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 45,
              "test_id"=> 34,
              "question"=> "そんな勉強のやり方で合格＿＿＿　＿＿＿　＿＿＊＿　＿＿＿見ればいいよ。",
              "image"=> null,
              "answer1"=> "やれる",
              "answer2"=> "やって",
              "answer3"=> "ものなら",
              "answer4"=> "できるか",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 46,
              "test_id"=> 34,
              "question"=> "日本人は、どこでも水がただて＿＿　＿＿　＿＊＿　＿＿　です。",
              "image"=> null,
              "answer1"=> "ありがたさを",
              "answer2"=> "飲める",
              "answer3"=> "がち",
              "answer4"=> "忘れ",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 47,
              "test_id"=> 34,
              "question"=> "歯医者に行くのは、大人に＿＿　＿＿　＿＊＿　＿＿＿　ありません。",
              "image"=> null,
              "answer1"=> "という",
              "answer2"=> "なれば",
              "answer3"=> "ものでは",
              "answer4"=> "平気になる",
              "correct_answer"=> "answer1",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 48,
              "test_id"=> 34,
              "question"=> "私が家の鍵を＿＿　＿＊＿　＿＿　＿＿泥棒に入られてしまった。",
              "image"=> null,
              "answer1"=> "ばかり",
              "answer2"=> "かけるのを",
              "answer3"=> "忘れた",
              "answer4"=> "に",
              "correct_answer"=> "answer3",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ],
            [
              "id"=> 49,
              "test_id"=> 34,
              "question"=> "A=> 「もう熱もないし、試験だから学校に行ってもいいよね。」B=> 「病気を人に＿＿　＿＊＿　＿＿　＿＿＿学校を休んだほうがいいわよ。」",
              "image"=> null,
              "answer1"=> "ある",
              "answer2"=> "以上は",
              "answer3"=> "移す",
              "answer4"=> "恐れが",
              "correct_answer"=> "answer4",
              "created_at"=> "2022-12-04T14:23:22.094Z",
              "updated_at"=> "2022-12-04T14:23:22.094Z"
            ]
        ]);
        // \App\Models\Question::factory(100)->create();
    }
}
